      SUBROUTINE RFILE(FNAME,CORE,LENGTH)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)

      CHARACTER*16 FNAME
      DIMENSION CORE(LENGTH)

      OPEN(UNIT=20001,FILE=FNAME,FORM='UNFORMATTED',
     &     ACCESS='SEQUENTIAL',STATUS='UNKNOWN')
      READ(20001)CORE
      CLOSE(UNIT=20001,STATUS='KEEP')

      RETURN
      END
