      SUBROUTINE WFILE(FNAME,CORE,LENGTH)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)

      CHARACTER*10 FNAME
      DIMENSION CORE(LENGTH)

      OPEN(UNIT=20001,FILE=FNAME,FORM='UNFORMATTED',
     &     ACCESS='SEQUENTIAL',STATUS='UNKNOWN')
      CLOSE(UNIT=20001,
     &      STATUS='DELETE')
      OPEN(UNIT=20001,FILE=FNAME,FORM='UNFORMATTED',
     &     ACCESS='SEQUENTIAL',STATUS='UNKNOWN')
      WRITE(20001)CORE
      CLOSE(UNIT=20001,STATUS='KEEP')

      RETURN
      END
