! THIS ROUTINE PRINTS THE FIRST LENGTH ELEMENTS OF VECTOR VEC
! AND THEIR INDICES IN I3,F13.10 FORMAT.  USEFUL FOR QUANTITIES
! WHICH HAVE MAGNITUDES COMPARABLE TO INTEGRALS AND AMPLITUDES.
      SUBROUTINE PRVECR(VEC,LENGTH)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /FILES/ LUOUT,MOINTS
      DIMENSION VEC(LENGTH)
      WRITE(LUOUT,100)(I,VEC(I),I=1,LENGTH)
100   FORMAT(4(1X,:'[',I4,']',F13.10))
      RETURN
      END

      
! THIS ROUTINE READ A BINARY FILE INTO A VECTOR.
      SUBROUTINE RFILE(FNAME,CORE,LENGTH)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      
      CHARACTER*16 FNAME
      DIMENSION CORE(LENGTH)
      
      OPEN(UNIT=20001,FILE=FNAME,FORM='UNFORMATTED',ACCESS='SEQUENTIAL',STATUS='UNKNOWN')
      READ(20001)CORE
      CLOSE(UNIT=20001,STATUS='KEEP')
      
      RETURN
      END

! THIS ROUTINE WRITE A BINARY FILE INTO A VECTOR.
      SUBROUTINE WFILE(FNAME,CORE,LENGTH)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      
      CHARACTER*10 FNAME
      DIMENSION CORE(LENGTH)
      
      OPEN(UNIT=20001,FILE=FNAME,FORM='UNFORMATTED',ACCESS='SEQUENTIAL',STATUS='UNKNOWN')
      CLOSE(UNIT=20001,STATUS='DELETE')
      OPEN(UNIT=20001,FILE=FNAME,FORM='UNFORMATTED',ACCESS='SEQUENTIAL',STATUS='UNKNOWN')
      WRITE(20001)CORE
      CLOSE(UNIT=20001,STATUS='KEEP')
      
      RETURN
      END
